apiVersion: v1
data:
    pycsw.yml: |+
        server:
            url: {{ .Values.pycsw.config.server.url }}
            mimetype: application/xml; charset=UTF-8
            encoding: UTF-8
            language: en-US
            maxrecords: 10
            gzip_compresslevel: 9
            workers: 1
            timeout: 60
        logging:
            level: DEBUG
        profiles:
            - apiso
        federatedcatalogues:
            - http://catalog.data.gov/csw
        manager:
            transactions: false
            allowed_ips:
                - 127.0.0.1
            csw_harvest_pagesize: 10
        metadata:
            identification:
                title: pycsw Geospatial Catalogue
                description: pycsw is an OARec and OGC CSW server implementation written in Python
                keywords:
                    - catalogue
                    - discovery
                    - metadata
                keywords_type: theme
                fees: None
                accessconstraints: None
                terms_of_service: https://creativecommons.org/licenses/by/4.0
                url: https://example.org
            license:
                name: CC-BY 4.0 license
                url: https://creativecommons.org/licenses/by/4.0
            provider:
                name: Organization Name
                url: https://pycsw.org
            contact:
                name: Lastname, Firstname
                position: Position Title
                address: Mailing Address
                city: City
                stateorprovince: Administrative Area
                postalcode: Zip or Postal Code
                country: Country
                phone: +xx-xxx-xxx-xxxx
                fax: +xx-xxx-xxx-xxxx
                email: you@example.org
                url: Contact URL
                hours: Mo-Fr 08:00-17:00
                instructions: During hours of service. Off on weekends.
                role: pointOfContact
            inspire:
                enabled: true
                languages_supported:
                    - eng
                    - gre
                default_language: eng
                date: YYYY-MM-DD
                gemet_keywords:
                    - Utility and governmental services
                conformity_service: notEvaluated
                contact_name: Organization Name
                contact_email: Email Address
                temp_extent:
                    begin: YYYY-MM-DD
                    end: YYYY-MM-DD
        repository:
            database: {{ .Values.pycsw.config.repository.database }}
            max_retries: 3
            table: records
            facets:
                - type
                - title
kind: ConfigMap
metadata:
  name: {{ .Values.pycsw.configmap_name }}
  namespace: {{ .Values.global.namespace }}
